### PR TITLE
Environment config 

### PR DESCRIPTION
**Pull request by skaasten**
test

### CODE REVIEW

**Comment by skaasten** [comment]
By analyzing the blame information on this pull request, we identified @dongweiming, @Friss and @vjeux to be potential reviewers

**Comment by skaasten** [comment]
By analyzing the blame information on this pull request, we identified @dongweiming, @Friss and @vjeux to be potential reviewers

**Comment by skaasten** [comment]
By analyzing the blame information on this pull request, we identified @dongweiming, @Friss and @vjeux to be potential reviewers

**Comment by vjeux** [comment]
Nice! Let me know when it is ready to be pulled in, it looks good :)

**Comment by skaasten** [comment]
By analyzing the blame information on this pull request, we identified @dongweiming, @Friss and @vjeux to be potential reviewers

**Comment by skaasten** [comment]
Thanks - I've tested it on regular github - just need to test it on enterprise again.

**Pull request merged**
